# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glovebox < Formula
  desc "CLI for sandboxed development environments using Docker"
  homepage "https://github.com/joelhelbling/glovebox"
  version "0.4.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joelhelbling/glovebox/releases/download/v0.4.7/glovebox_0.4.7_darwin_amd64.tar.gz"
      sha256 "6d0c1bb326d7afda3e52d4945b66106cf9267dd3d0a918b763fb195bad0cd80f"

      def install
        bin.install "glovebox"
        bin.install_symlink "glovebox" => "gb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joelhelbling/glovebox/releases/download/v0.4.7/glovebox_0.4.7_darwin_arm64.tar.gz"
      sha256 "dcef1c9638bcb350f11867c680df368548c2b3844dace6601ca119076406920d"

      def install
        bin.install "glovebox"
        bin.install_symlink "glovebox" => "gb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joelhelbling/glovebox/releases/download/v0.4.7/glovebox_0.4.7_linux_amd64.tar.gz"
      sha256 "62903b19b1a5933b5f06394d98a16954df74a8fa9508ffbe60ead52a9103bbca"
      def install
        bin.install "glovebox"
        bin.install_symlink "glovebox" => "gb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joelhelbling/glovebox/releases/download/v0.4.7/glovebox_0.4.7_linux_arm64.tar.gz"
      sha256 "1c77590eecc9c89dd4c326a959782aadfc96566d9a062d307794592546e8b622"
      def install
        bin.install "glovebox"
        bin.install_symlink "glovebox" => "gb"
      end
    end
  end

  test do
    system "#{bin}/glovebox", "-v"
  end
end
